/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2RouteImport } from './routes/v2'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as V2CompareRouteImport } from './routes/v2/compare'
import { Route as V2EngineRouteImport } from './routes/v2/engine'
import { Route as V2HourlyRouteImport } from './routes/v2/hourly'
import { Route as V2MarketRouteImport } from './routes/v2/market'
import { Route as V2MatrixRouteImport } from './routes/v2/matrix'
import { Route as V2PresetsRouteImport } from './routes/v2/presets'
import { Route as V2ResultsRouteImport } from './routes/v2/results'
import { Route as V2SettingsRouteImport } from './routes/v2/settings'
import { Route as V2StagesRouteImport } from './routes/v2/stages'
import { Route as V2StatisticsRouteImport } from './routes/v2/statistics'
import { Route as V2TradingRouteImport } from './routes/v2/trading'
import { Route as ApiCoreEventsRouteImport } from './routes/api/core/events'
import { Route as V2ConfigIdRouteImport } from './routes/v2/config.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const V2CompareRoute = V2CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => V2Route,
} as any)
const V2EngineRoute = V2EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => V2Route,
} as any)
const V2HourlyRoute = V2HourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => V2Route,
} as any)
const V2MarketRoute = V2MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => V2Route,
} as any)
const V2MatrixRoute = V2MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => V2Route,
} as any)
const V2PresetsRoute = V2PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => V2Route,
} as any)
const V2ResultsRoute = V2ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => V2Route,
} as any)
const V2SettingsRoute = V2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => V2Route,
} as any)
const V2StagesRoute = V2StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => V2Route,
} as any)
const V2StatisticsRoute = V2StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => V2Route,
} as any)
const V2TradingRoute = V2TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => V2Route,
} as any)
const ApiCoreEventsRoute = ApiCoreEventsRouteImport.update({
  id: '/api/core/events',
  path: '/api/core/events',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ConfigIdRoute = V2ConfigIdRouteImport.update({
  id: '/config/$id',
  path: '/config/$id',
  getParentRoute: () => V2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/presets': typeof V2PresetsRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/statistics': typeof V2StatisticsRoute
  '/v2/trading': typeof V2TradingRoute
  '/v2/': typeof V2IndexRoute
  '/api/core/events': typeof ApiCoreEventsRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/presets': typeof V2PresetsRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/statistics': typeof V2StatisticsRoute
  '/v2/trading': typeof V2TradingRoute
  '/v2': typeof V2IndexRoute
  '/api/core/events': typeof ApiCoreEventsRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/presets': typeof V2PresetsRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/statistics': typeof V2StatisticsRoute
  '/v2/trading': typeof V2TradingRoute
  '/v2/': typeof V2IndexRoute
  '/api/core/events': typeof ApiCoreEventsRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v2'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/presets'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/statistics'
    | '/v2/trading'
    | '/v2/'
    | '/api/core/events'
    | '/v2/config/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/presets'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/statistics'
    | '/v2/trading'
    | '/v2'
    | '/api/core/events'
    | '/v2/config/$id'
  id:
    | '__root__'
    | '/'
    | '/v2'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/presets'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/statistics'
    | '/v2/trading'
    | '/v2/'
    | '/api/core/events'
    | '/v2/config/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2Route: typeof V2RouteWithChildren
  ApiCoreEventsRoute: typeof ApiCoreEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/compare': {
      id: '/v2/compare'
      path: '/compare'
      fullPath: '/v2/compare'
      preLoaderRoute: typeof V2CompareRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/engine': {
      id: '/v2/engine'
      path: '/engine'
      fullPath: '/v2/engine'
      preLoaderRoute: typeof V2EngineRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/hourly': {
      id: '/v2/hourly'
      path: '/hourly'
      fullPath: '/v2/hourly'
      preLoaderRoute: typeof V2HourlyRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/market': {
      id: '/v2/market'
      path: '/market'
      fullPath: '/v2/market'
      preLoaderRoute: typeof V2MarketRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/matrix': {
      id: '/v2/matrix'
      path: '/matrix'
      fullPath: '/v2/matrix'
      preLoaderRoute: typeof V2MatrixRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/presets': {
      id: '/v2/presets'
      path: '/presets'
      fullPath: '/v2/presets'
      preLoaderRoute: typeof V2PresetsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/results': {
      id: '/v2/results'
      path: '/results'
      fullPath: '/v2/results'
      preLoaderRoute: typeof V2ResultsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/settings': {
      id: '/v2/settings'
      path: '/settings'
      fullPath: '/v2/settings'
      preLoaderRoute: typeof V2SettingsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/stages': {
      id: '/v2/stages'
      path: '/stages'
      fullPath: '/v2/stages'
      preLoaderRoute: typeof V2StagesRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/statistics': {
      id: '/v2/statistics'
      path: '/statistics'
      fullPath: '/v2/statistics'
      preLoaderRoute: typeof V2StatisticsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/trading': {
      id: '/v2/trading'
      path: '/trading'
      fullPath: '/v2/trading'
      preLoaderRoute: typeof V2TradingRouteImport
      parentRoute: typeof V2Route
    }
    '/api/core/events': {
      id: '/api/core/events'
      path: '/api/core/events'
      fullPath: '/api/core/events'
      preLoaderRoute: typeof ApiCoreEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/config/$id': {
      id: '/v2/config/$id'
      path: '/config/$id'
      fullPath: '/v2/config/$id'
      preLoaderRoute: typeof V2ConfigIdRouteImport
      parentRoute: typeof V2Route
    }
  }
}

interface V2RouteChildren {
  V2CompareRoute: typeof V2CompareRoute
  V2EngineRoute: typeof V2EngineRoute
  V2HourlyRoute: typeof V2HourlyRoute
  V2MarketRoute: typeof V2MarketRoute
  V2MatrixRoute: typeof V2MatrixRoute
  V2PresetsRoute: typeof V2PresetsRoute
  V2ResultsRoute: typeof V2ResultsRoute
  V2SettingsRoute: typeof V2SettingsRoute
  V2StagesRoute: typeof V2StagesRoute
  V2StatisticsRoute: typeof V2StatisticsRoute
  V2TradingRoute: typeof V2TradingRoute
  V2IndexRoute: typeof V2IndexRoute
  V2ConfigIdRoute: typeof V2ConfigIdRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2CompareRoute: V2CompareRoute,
  V2EngineRoute: V2EngineRoute,
  V2HourlyRoute: V2HourlyRoute,
  V2MarketRoute: V2MarketRoute,
  V2MatrixRoute: V2MatrixRoute,
  V2PresetsRoute: V2PresetsRoute,
  V2ResultsRoute: V2ResultsRoute,
  V2SettingsRoute: V2SettingsRoute,
  V2StagesRoute: V2StagesRoute,
  V2StatisticsRoute: V2StatisticsRoute,
  V2TradingRoute: V2TradingRoute,
  V2IndexRoute: V2IndexRoute,
  V2ConfigIdRoute: V2ConfigIdRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2Route: V2RouteWithChildren,
  ApiCoreEventsRoute: ApiCoreEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
