/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as V2RouteImport } from './routes/v2'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskSplatRouteImport } from './routes/_desk/$'
import { Route as DeskBotsRouteImport } from './routes/_desk/bots'
import { Route as DeskCombinationsRouteImport } from './routes/_desk/combinations'
import { Route as DeskConnectionsRouteImport } from './routes/_desk/connections'
import { Route as DeskEngineRouteImport } from './routes/_desk/engine'
import { Route as DeskHeatmapRouteImport } from './routes/_desk/heatmap'
import { Route as DeskLanesRouteImport } from './routes/_desk/lanes'
import { Route as DeskLogisticsRouteImport } from './routes/_desk/logistics'
import { Route as DeskModernRouteImport } from './routes/_desk/modern'
import { Route as DeskOrdersRouteImport } from './routes/_desk/orders'
import { Route as DeskPerformanceRouteImport } from './routes/_desk/performance'
import { Route as DeskPositionsRouteImport } from './routes/_desk/positions'
import { Route as DeskReplayRouteImport } from './routes/_desk/replay'
import { Route as DeskResultsRouteImport } from './routes/_desk/results'
import { Route as DeskSettingsRouteImport } from './routes/_desk/settings'
import { Route as DeskStatisticsRouteImport } from './routes/_desk/statistics'
import { Route as DeskStrategiesRouteImport } from './routes/_desk/strategies'
import { Route as DeskSystemRouteImport } from './routes/_desk/system'
import { Route as DeskTacticsRouteImport } from './routes/_desk/tactics'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as V2CompareRouteImport } from './routes/v2/compare'
import { Route as V2EngineRouteImport } from './routes/v2/engine'
import { Route as V2HourlyRouteImport } from './routes/v2/hourly'
import { Route as V2MarketRouteImport } from './routes/v2/market'
import { Route as V2MatrixRouteImport } from './routes/v2/matrix'
import { Route as V2ResultsRouteImport } from './routes/v2/results'
import { Route as V2SettingsRouteImport } from './routes/v2/settings'
import { Route as V2StagesRouteImport } from './routes/v2/stages'
import { Route as V2TradingRouteImport } from './routes/v2/trading'
import { Route as V2ConfigIdRouteImport } from './routes/v2/config.$id'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSplatRoute = DeskSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBotsRoute = DeskBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCombinationsRoute = DeskCombinationsRouteImport.update({
  id: '/combinations',
  path: '/combinations',
  getParentRoute: () => DeskRoute,
} as any)
const DeskConnectionsRoute = DeskConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DeskRoute,
} as any)
const DeskEngineRoute = DeskEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => DeskRoute,
} as any)
const DeskHeatmapRoute = DeskHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLanesRoute = DeskLanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLogisticsRoute = DeskLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DeskRoute,
} as any)
const DeskModernRoute = DeskModernRouteImport.update({
  id: '/modern',
  path: '/modern',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOrdersRoute = DeskOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPerformanceRoute = DeskPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPositionsRoute = DeskPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReplayRoute = DeskReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => DeskRoute,
} as any)
const DeskResultsRoute = DeskResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskStatisticsRoute = DeskStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DeskRoute,
} as any)
const DeskStrategiesRoute = DeskStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSystemRoute = DeskSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTacticsRoute = DeskTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => DeskRoute,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const V2CompareRoute = V2CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => V2Route,
} as any)
const V2EngineRoute = V2EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => V2Route,
} as any)
const V2HourlyRoute = V2HourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => V2Route,
} as any)
const V2MarketRoute = V2MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => V2Route,
} as any)
const V2MatrixRoute = V2MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => V2Route,
} as any)
const V2ResultsRoute = V2ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => V2Route,
} as any)
const V2SettingsRoute = V2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => V2Route,
} as any)
const V2StagesRoute = V2StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => V2Route,
} as any)
const V2TradingRoute = V2TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => V2Route,
} as any)
const V2ConfigIdRoute = V2ConfigIdRouteImport.update({
  id: '/config/$id',
  path: '/config/$id',
  getParentRoute: () => V2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/v2': typeof V2RouteWithChildren
  '/$': typeof DeskSplatRoute
  '/bots': typeof DeskBotsRoute
  '/combinations': typeof DeskCombinationsRoute
  '/connections': typeof DeskConnectionsRoute
  '/engine': typeof DeskEngineRoute
  '/heatmap': typeof DeskHeatmapRoute
  '/lanes': typeof DeskLanesRoute
  '/logistics': typeof DeskLogisticsRoute
  '/modern': typeof DeskModernRoute
  '/orders': typeof DeskOrdersRoute
  '/performance': typeof DeskPerformanceRoute
  '/positions': typeof DeskPositionsRoute
  '/replay': typeof DeskReplayRoute
  '/results': typeof DeskResultsRoute
  '/settings': typeof DeskSettingsRoute
  '/statistics': typeof DeskStatisticsRoute
  '/strategies': typeof DeskStrategiesRoute
  '/system': typeof DeskSystemRoute
  '/tactics': typeof DeskTacticsRoute
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/trading': typeof V2TradingRoute
  '/v2/': typeof V2IndexRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof DeskSplatRoute
  '/bots': typeof DeskBotsRoute
  '/combinations': typeof DeskCombinationsRoute
  '/connections': typeof DeskConnectionsRoute
  '/engine': typeof DeskEngineRoute
  '/heatmap': typeof DeskHeatmapRoute
  '/lanes': typeof DeskLanesRoute
  '/logistics': typeof DeskLogisticsRoute
  '/modern': typeof DeskModernRoute
  '/orders': typeof DeskOrdersRoute
  '/performance': typeof DeskPerformanceRoute
  '/positions': typeof DeskPositionsRoute
  '/replay': typeof DeskReplayRoute
  '/results': typeof DeskResultsRoute
  '/settings': typeof DeskSettingsRoute
  '/statistics': typeof DeskStatisticsRoute
  '/strategies': typeof DeskStrategiesRoute
  '/system': typeof DeskSystemRoute
  '/tactics': typeof DeskTacticsRoute
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/trading': typeof V2TradingRoute
  '/': typeof DeskIndexRoute
  '/v2': typeof V2IndexRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/v2': typeof V2RouteWithChildren
  '/_desk/$': typeof DeskSplatRoute
  '/_desk/bots': typeof DeskBotsRoute
  '/_desk/combinations': typeof DeskCombinationsRoute
  '/_desk/connections': typeof DeskConnectionsRoute
  '/_desk/engine': typeof DeskEngineRoute
  '/_desk/heatmap': typeof DeskHeatmapRoute
  '/_desk/lanes': typeof DeskLanesRoute
  '/_desk/logistics': typeof DeskLogisticsRoute
  '/_desk/modern': typeof DeskModernRoute
  '/_desk/orders': typeof DeskOrdersRoute
  '/_desk/performance': typeof DeskPerformanceRoute
  '/_desk/positions': typeof DeskPositionsRoute
  '/_desk/replay': typeof DeskReplayRoute
  '/_desk/results': typeof DeskResultsRoute
  '/_desk/settings': typeof DeskSettingsRoute
  '/_desk/statistics': typeof DeskStatisticsRoute
  '/_desk/strategies': typeof DeskStrategiesRoute
  '/_desk/system': typeof DeskSystemRoute
  '/_desk/tactics': typeof DeskTacticsRoute
  '/v2/compare': typeof V2CompareRoute
  '/v2/engine': typeof V2EngineRoute
  '/v2/hourly': typeof V2HourlyRoute
  '/v2/market': typeof V2MarketRoute
  '/v2/matrix': typeof V2MatrixRoute
  '/v2/results': typeof V2ResultsRoute
  '/v2/settings': typeof V2SettingsRoute
  '/v2/stages': typeof V2StagesRoute
  '/v2/trading': typeof V2TradingRoute
  '/_desk/': typeof DeskIndexRoute
  '/v2/': typeof V2IndexRoute
  '/v2/config/$id': typeof V2ConfigIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v2'
    | '/$'
    | '/bots'
    | '/combinations'
    | '/connections'
    | '/engine'
    | '/heatmap'
    | '/lanes'
    | '/logistics'
    | '/modern'
    | '/orders'
    | '/performance'
    | '/positions'
    | '/replay'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/strategies'
    | '/system'
    | '/tactics'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/trading'
    | '/v2/'
    | '/v2/config/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/bots'
    | '/combinations'
    | '/connections'
    | '/engine'
    | '/heatmap'
    | '/lanes'
    | '/logistics'
    | '/modern'
    | '/orders'
    | '/performance'
    | '/positions'
    | '/replay'
    | '/results'
    | '/settings'
    | '/statistics'
    | '/strategies'
    | '/system'
    | '/tactics'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/trading'
    | '/'
    | '/v2'
    | '/v2/config/$id'
  id:
    | '__root__'
    | '/_desk'
    | '/v2'
    | '/_desk/$'
    | '/_desk/bots'
    | '/_desk/combinations'
    | '/_desk/connections'
    | '/_desk/engine'
    | '/_desk/heatmap'
    | '/_desk/lanes'
    | '/_desk/logistics'
    | '/_desk/modern'
    | '/_desk/orders'
    | '/_desk/performance'
    | '/_desk/positions'
    | '/_desk/replay'
    | '/_desk/results'
    | '/_desk/settings'
    | '/_desk/statistics'
    | '/_desk/strategies'
    | '/_desk/system'
    | '/_desk/tactics'
    | '/v2/compare'
    | '/v2/engine'
    | '/v2/hourly'
    | '/v2/market'
    | '/v2/matrix'
    | '/v2/results'
    | '/v2/settings'
    | '/v2/stages'
    | '/v2/trading'
    | '/_desk/'
    | '/v2/'
    | '/v2/config/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
  V2Route: typeof V2RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/$': {
      id: '/_desk/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DeskSplatRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/bots': {
      id: '/_desk/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof DeskBotsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/combinations': {
      id: '/_desk/combinations'
      path: '/combinations'
      fullPath: '/combinations'
      preLoaderRoute: typeof DeskCombinationsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/connections': {
      id: '/_desk/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DeskConnectionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/engine': {
      id: '/_desk/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof DeskEngineRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/heatmap': {
      id: '/_desk/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof DeskHeatmapRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/lanes': {
      id: '/_desk/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof DeskLanesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/logistics': {
      id: '/_desk/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof DeskLogisticsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/modern': {
      id: '/_desk/modern'
      path: '/modern'
      fullPath: '/modern'
      preLoaderRoute: typeof DeskModernRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/orders': {
      id: '/_desk/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DeskOrdersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/performance': {
      id: '/_desk/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof DeskPerformanceRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/positions': {
      id: '/_desk/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof DeskPositionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/replay': {
      id: '/_desk/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof DeskReplayRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/results': {
      id: '/_desk/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof DeskResultsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/settings': {
      id: '/_desk/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/statistics': {
      id: '/_desk/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof DeskStatisticsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/strategies': {
      id: '/_desk/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof DeskStrategiesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/system': {
      id: '/_desk/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DeskSystemRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/tactics': {
      id: '/_desk/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof DeskTacticsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/compare': {
      id: '/v2/compare'
      path: '/compare'
      fullPath: '/v2/compare'
      preLoaderRoute: typeof V2CompareRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/engine': {
      id: '/v2/engine'
      path: '/engine'
      fullPath: '/v2/engine'
      preLoaderRoute: typeof V2EngineRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/hourly': {
      id: '/v2/hourly'
      path: '/hourly'
      fullPath: '/v2/hourly'
      preLoaderRoute: typeof V2HourlyRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/market': {
      id: '/v2/market'
      path: '/market'
      fullPath: '/v2/market'
      preLoaderRoute: typeof V2MarketRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/matrix': {
      id: '/v2/matrix'
      path: '/matrix'
      fullPath: '/v2/matrix'
      preLoaderRoute: typeof V2MatrixRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/results': {
      id: '/v2/results'
      path: '/results'
      fullPath: '/v2/results'
      preLoaderRoute: typeof V2ResultsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/settings': {
      id: '/v2/settings'
      path: '/settings'
      fullPath: '/v2/settings'
      preLoaderRoute: typeof V2SettingsRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/stages': {
      id: '/v2/stages'
      path: '/stages'
      fullPath: '/v2/stages'
      preLoaderRoute: typeof V2StagesRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/trading': {
      id: '/v2/trading'
      path: '/trading'
      fullPath: '/v2/trading'
      preLoaderRoute: typeof V2TradingRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/config/$id': {
      id: '/v2/config/$id'
      path: '/config/$id'
      fullPath: '/v2/config/$id'
      preLoaderRoute: typeof V2ConfigIdRouteImport
      parentRoute: typeof V2Route
    }
  }
}

interface DeskRouteChildren {
  DeskSplatRoute: typeof DeskSplatRoute
  DeskBotsRoute: typeof DeskBotsRoute
  DeskCombinationsRoute: typeof DeskCombinationsRoute
  DeskConnectionsRoute: typeof DeskConnectionsRoute
  DeskEngineRoute: typeof DeskEngineRoute
  DeskHeatmapRoute: typeof DeskHeatmapRoute
  DeskLanesRoute: typeof DeskLanesRoute
  DeskLogisticsRoute: typeof DeskLogisticsRoute
  DeskModernRoute: typeof DeskModernRoute
  DeskOrdersRoute: typeof DeskOrdersRoute
  DeskPerformanceRoute: typeof DeskPerformanceRoute
  DeskPositionsRoute: typeof DeskPositionsRoute
  DeskReplayRoute: typeof DeskReplayRoute
  DeskResultsRoute: typeof DeskResultsRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskStatisticsRoute: typeof DeskStatisticsRoute
  DeskStrategiesRoute: typeof DeskStrategiesRoute
  DeskSystemRoute: typeof DeskSystemRoute
  DeskTacticsRoute: typeof DeskTacticsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskSplatRoute: DeskSplatRoute,
  DeskBotsRoute: DeskBotsRoute,
  DeskCombinationsRoute: DeskCombinationsRoute,
  DeskConnectionsRoute: DeskConnectionsRoute,
  DeskEngineRoute: DeskEngineRoute,
  DeskHeatmapRoute: DeskHeatmapRoute,
  DeskLanesRoute: DeskLanesRoute,
  DeskLogisticsRoute: DeskLogisticsRoute,
  DeskModernRoute: DeskModernRoute,
  DeskOrdersRoute: DeskOrdersRoute,
  DeskPerformanceRoute: DeskPerformanceRoute,
  DeskPositionsRoute: DeskPositionsRoute,
  DeskReplayRoute: DeskReplayRoute,
  DeskResultsRoute: DeskResultsRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskStatisticsRoute: DeskStatisticsRoute,
  DeskStrategiesRoute: DeskStrategiesRoute,
  DeskSystemRoute: DeskSystemRoute,
  DeskTacticsRoute: DeskTacticsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface V2RouteChildren {
  V2CompareRoute: typeof V2CompareRoute
  V2EngineRoute: typeof V2EngineRoute
  V2HourlyRoute: typeof V2HourlyRoute
  V2MarketRoute: typeof V2MarketRoute
  V2MatrixRoute: typeof V2MatrixRoute
  V2ResultsRoute: typeof V2ResultsRoute
  V2SettingsRoute: typeof V2SettingsRoute
  V2StagesRoute: typeof V2StagesRoute
  V2TradingRoute: typeof V2TradingRoute
  V2IndexRoute: typeof V2IndexRoute
  V2ConfigIdRoute: typeof V2ConfigIdRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2CompareRoute: V2CompareRoute,
  V2EngineRoute: V2EngineRoute,
  V2HourlyRoute: V2HourlyRoute,
  V2MarketRoute: V2MarketRoute,
  V2MatrixRoute: V2MatrixRoute,
  V2ResultsRoute: V2ResultsRoute,
  V2SettingsRoute: V2SettingsRoute,
  V2StagesRoute: V2StagesRoute,
  V2TradingRoute: V2TradingRoute,
  V2IndexRoute: V2IndexRoute,
  V2ConfigIdRoute: V2ConfigIdRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
  V2Route: V2RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
